// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Host.TemplateFile = C:\Dev\HyperSlackers\HyperSlackers.Localization\Demo.Resources\T4resx.tt

// Make sure the compiler doesn't complain about missing XML comments
#pragma warning disable 1591

namespace Localized
{
	using SmartFormat;
	using System;
	using System.Collections.Generic;
	using System.ComponentModel;
	using System.Diagnostics;
	using System.Linq;
	using System.Reflection;
	using System.Runtime.CompilerServices;
	using System.Text;
	using System.Threading;
	using System.Threading.Tasks;
	using System.Web;
	using System.Web.Mvc;

	[DebuggerNonUserCodeAttribute()]
	[CompilerGeneratedAttribute()]
	public static class Models
	{
		#region Resource Manager
		
		private static global::System.Resources.ResourceManager resourceMan;
	
		/// <summary> Returns the cached ResourceManager instance used by this class. </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager 
		{
			get
			{
				if (object.ReferenceEquals(Models.resourceMan, null))
				{
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localized.Models", typeof(Models).Assembly);
					// ???? global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("", typeof().Assembly);
					resourceMan = temp;
				}
			
				return resourceMan;
			}
		}
		
		/// <summary> Returns the formatted resource string. </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		private static string GetResourceString(string key)
		{
			var culture = Thread.CurrentThread.CurrentCulture;
			var str = ResourceManager.GetString(key, culture);
			
			return str;
		}
		
		/// <summary> Returns the formatted resource string. </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		private static HtmlString GetResourceHtmlString(string key)
		{
			var str = GetResourceString(key);
			
			return new HtmlString(str);
		}
		
		#endregion Resource Manager
		
		#region Keys
		
		/// <summary> Confirm Password (from resx) </summary>
		public static string ConfirmPassword { get { return GetResourceString("ConfirmPassword"); } }
		/// <summary> Demo One Model (from resx) </summary>
		public static string DemoOneModel { get { return GetResourceString("DemoOneModel"); } }
		/// <summary> String Three (DemoOneModel) (from resx) </summary>
		public static string DemoOneModel_StringThree { get { return GetResourceString("DemoOneModel_StringThree"); } }
		/// <summary> Email (from resx) </summary>
		public static string Email { get { return GetResourceString("Email"); } }
		/// <summary> Password (from resx) </summary>
		public static string Password { get { return GetResourceString("Password"); } }
		/// <summary> Positive Number (from resx) </summary>
		public static string PositiveNumber { get { return GetResourceString("PositiveNumber"); } }
		/// <summary> Number between 10 and 20 (from resx) </summary>
		public static string RangedNumber { get { return GetResourceString("RangedNumber"); } }
		/// <summary> String Three (from resx) </summary>
		public static string StringThree { get { return GetResourceString("StringThree"); } }
		/// <summary> String Two (from resx) </summary>
		public static string StringTwo { get { return GetResourceString("StringTwo"); } }
		
		#endregion Keys
		
		#region Key Names
		
		public static class KeyNames
		{
			public const string ConfirmPassword = "ConfirmPassword";
			public const string DemoOneModel = "DemoOneModel";
			public const string DemoOneModel_StringThree = "DemoOneModel_StringThree";
			public const string Email = "Email";
			public const string Password = "Password";
			public const string PositiveNumber = "PositiveNumber";
			public const string RangedNumber = "RangedNumber";
			public const string StringThree = "StringThree";
			public const string StringTwo = "StringTwo";
		}
		
		#endregion Key Names
	}
	

}

